# Generated by Django 4.1.7 on 2023-04-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentarioBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaComentarioBlog', models.DateField()),
                ('textComentarioBlog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickUser', models.CharField(max_length=15)),
                ('nombreUser', models.CharField(max_length=40)),
                ('apellidoUser', models.CharField(max_length=40)),
                ('edadUser', models.IntegerField()),
                ('emailUser', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittleBlogs', models.CharField(max_length=42)),
                ('fechaBlogs', models.DateField()),
                ('textBlogs', models.TextField()),
                ('imgBlogs', models.ImageField(upload_to='publicacion_imagenes')),
                ('autorBlogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsApp.users')),
            ],
        ),
    ]
