# Generated by Django 4.1.7 on 2023-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=42)),
                ('fechaCreacion', models.DateField()),
                ('textblog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUser', models.CharField(max_length=15)),
                ('pwUser', models.CharField(max_length=100)),
                ('emailUser', models.EmailField(max_length=254)),
            ],
        ),
    ]
